import = [
    #"~/.config/alacritty/themes/themes/ayu_dark.toml"
    #"~/.config/alacritty/themes/themes/coolnight.toml"
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

live_config_reload = true

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 30
padding.y = 30

decorations = "None"
opacity = 1.0
dynamic_title = true
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
#normal.family = ""
size = 20

# BEGIN WAL
[colors.primary]
background = '#130e0c'
foreground = '#e1cdbe'

[colors.cursor]
text   = '#130e0c' # Apply background color to color of text inside cursor
cursor = '#e1cdbe' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#130e0c' # Same as above
cursor  = '#e1cdbe'

[colors.search.matches]
foreground = '#130e0c' # Same as above
background = '#e1cdbe' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#9d8f85'
background = '#e1cdbe'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#130e0c'
red     = '#BA5432'
green   = '#976E56'
yellow  = '#7F817B'
blue    = '#AF8A6E'
magenta = '#E5A24C'
cyan    = '#D49A6B'
white   = '#e1cdbe'

[colors.bright]
black   = '#9d8f85'
red     = '#BA5432'
green   = '#976E56'
yellow  = '#7F817B'
blue    = '#AF8A6E'
magenta = '#E5A24C'
cyan    = '#D49A6B'
white   = '#e1cdbe'
# END WAL
