
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 30
padding.y = 30

decorations = "None"
opacity = 1.0
dynamic_title = true
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
#normal.family = ""
size = 20

[general]

live_config_reload = true
import = [
    #"~/.config/alacritty/themes/themes/ayu_dark.toml"
    "~/.config/alacritty/themes/themes/coolnight.toml"
    #"~/.config/alacritty/themes/themes/nord.toml"
]

# BEGIN WAL
# END WAL
